# Generated by Django 5.0 on 2024-01-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foodImg',
            field=models.ImageField(default='food-default.jpg', upload_to='food_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(null=True),
        ),
    ]
